// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.DataModel;

namespace dotnet5sample.Server.Migrations
{
    [DbContext(typeof(MyDb))]
    partial class MyDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("PostTag", b =>
                {
                    b.Property<int>("PostsId")
                        .HasColumnType("int");

                    b.Property<int>("TagsId")
                        .HasColumnType("int");

                    b.HasKey("PostsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("PostTag");
                });

            modelBuilder.Entity("Server.DataModel.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "Body 1",
                            Title = "Titolo 1"
                        },
                        new
                        {
                            Id = 2,
                            Body = "Body 2",
                            Title = "Titolo 2"
                        },
                        new
                        {
                            Id = 3,
                            Body = "Body 3",
                            Title = "Titolo 3"
                        },
                        new
                        {
                            Id = 4,
                            Body = "Body 4",
                            Title = "Titolo 4"
                        },
                        new
                        {
                            Id = 5,
                            Body = "Body 5",
                            Title = "Titolo 5"
                        },
                        new
                        {
                            Id = 6,
                            Body = "Body 6",
                            Title = "Titolo 6"
                        },
                        new
                        {
                            Id = 7,
                            Body = "Body 7",
                            Title = "Titolo 7"
                        },
                        new
                        {
                            Id = 8,
                            Body = "Body 8",
                            Title = "Titolo 8"
                        },
                        new
                        {
                            Id = 9,
                            Body = "Body 9",
                            Title = "Titolo 9"
                        },
                        new
                        {
                            Id = 10,
                            Body = "Body 10",
                            Title = "Titolo 10"
                        },
                        new
                        {
                            Id = 11,
                            Body = "Body 11",
                            Title = "Titolo 11"
                        },
                        new
                        {
                            Id = 12,
                            Body = "Body 12",
                            Title = "Titolo 12"
                        },
                        new
                        {
                            Id = 13,
                            Body = "Body 13",
                            Title = "Titolo 13"
                        },
                        new
                        {
                            Id = 14,
                            Body = "Body 14",
                            Title = "Titolo 14"
                        },
                        new
                        {
                            Id = 15,
                            Body = "Body 15",
                            Title = "Titolo 15"
                        },
                        new
                        {
                            Id = 16,
                            Body = "Body 16",
                            Title = "Titolo 16"
                        },
                        new
                        {
                            Id = 17,
                            Body = "Body 17",
                            Title = "Titolo 17"
                        },
                        new
                        {
                            Id = 18,
                            Body = "Body 18",
                            Title = "Titolo 18"
                        },
                        new
                        {
                            Id = 19,
                            Body = "Body 19",
                            Title = "Titolo 19"
                        },
                        new
                        {
                            Id = 20,
                            Body = "Body 20",
                            Title = "Titolo 20"
                        },
                        new
                        {
                            Id = 21,
                            Body = "Body 21",
                            Title = "Titolo 21"
                        },
                        new
                        {
                            Id = 22,
                            Body = "Body 22",
                            Title = "Titolo 22"
                        },
                        new
                        {
                            Id = 23,
                            Body = "Body 23",
                            Title = "Titolo 23"
                        },
                        new
                        {
                            Id = 24,
                            Body = "Body 24",
                            Title = "Titolo 24"
                        },
                        new
                        {
                            Id = 25,
                            Body = "Body 25",
                            Title = "Titolo 25"
                        },
                        new
                        {
                            Id = 26,
                            Body = "Body 26",
                            Title = "Titolo 26"
                        },
                        new
                        {
                            Id = 27,
                            Body = "Body 27",
                            Title = "Titolo 27"
                        },
                        new
                        {
                            Id = 28,
                            Body = "Body 28",
                            Title = "Titolo 28"
                        },
                        new
                        {
                            Id = 29,
                            Body = "Body 29",
                            Title = "Titolo 29"
                        },
                        new
                        {
                            Id = 30,
                            Body = "Body 30",
                            Title = "Titolo 30"
                        },
                        new
                        {
                            Id = 31,
                            Body = "Body 31",
                            Title = "Titolo 31"
                        },
                        new
                        {
                            Id = 32,
                            Body = "Body 32",
                            Title = "Titolo 32"
                        },
                        new
                        {
                            Id = 33,
                            Body = "Body 33",
                            Title = "Titolo 33"
                        },
                        new
                        {
                            Id = 34,
                            Body = "Body 34",
                            Title = "Titolo 34"
                        },
                        new
                        {
                            Id = 35,
                            Body = "Body 35",
                            Title = "Titolo 35"
                        },
                        new
                        {
                            Id = 36,
                            Body = "Body 36",
                            Title = "Titolo 36"
                        },
                        new
                        {
                            Id = 37,
                            Body = "Body 37",
                            Title = "Titolo 37"
                        },
                        new
                        {
                            Id = 38,
                            Body = "Body 38",
                            Title = "Titolo 38"
                        },
                        new
                        {
                            Id = 39,
                            Body = "Body 39",
                            Title = "Titolo 39"
                        },
                        new
                        {
                            Id = 40,
                            Body = "Body 40",
                            Title = "Titolo 40"
                        },
                        new
                        {
                            Id = 41,
                            Body = "Body 41",
                            Title = "Titolo 41"
                        },
                        new
                        {
                            Id = 42,
                            Body = "Body 42",
                            Title = "Titolo 42"
                        },
                        new
                        {
                            Id = 43,
                            Body = "Body 43",
                            Title = "Titolo 43"
                        },
                        new
                        {
                            Id = 44,
                            Body = "Body 44",
                            Title = "Titolo 44"
                        },
                        new
                        {
                            Id = 45,
                            Body = "Body 45",
                            Title = "Titolo 45"
                        },
                        new
                        {
                            Id = 46,
                            Body = "Body 46",
                            Title = "Titolo 46"
                        },
                        new
                        {
                            Id = 47,
                            Body = "Body 47",
                            Title = "Titolo 47"
                        },
                        new
                        {
                            Id = 48,
                            Body = "Body 48",
                            Title = "Titolo 48"
                        },
                        new
                        {
                            Id = 49,
                            Body = "Body 49",
                            Title = "Titolo 49"
                        },
                        new
                        {
                            Id = 50,
                            Body = "Body 50",
                            Title = "Titolo 50"
                        },
                        new
                        {
                            Id = 51,
                            Body = "Body 51",
                            Title = "Titolo 51"
                        },
                        new
                        {
                            Id = 52,
                            Body = "Body 52",
                            Title = "Titolo 52"
                        },
                        new
                        {
                            Id = 53,
                            Body = "Body 53",
                            Title = "Titolo 53"
                        },
                        new
                        {
                            Id = 54,
                            Body = "Body 54",
                            Title = "Titolo 54"
                        },
                        new
                        {
                            Id = 55,
                            Body = "Body 55",
                            Title = "Titolo 55"
                        },
                        new
                        {
                            Id = 56,
                            Body = "Body 56",
                            Title = "Titolo 56"
                        },
                        new
                        {
                            Id = 57,
                            Body = "Body 57",
                            Title = "Titolo 57"
                        },
                        new
                        {
                            Id = 58,
                            Body = "Body 58",
                            Title = "Titolo 58"
                        },
                        new
                        {
                            Id = 59,
                            Body = "Body 59",
                            Title = "Titolo 59"
                        },
                        new
                        {
                            Id = 60,
                            Body = "Body 60",
                            Title = "Titolo 60"
                        },
                        new
                        {
                            Id = 61,
                            Body = "Body 61",
                            Title = "Titolo 61"
                        },
                        new
                        {
                            Id = 62,
                            Body = "Body 62",
                            Title = "Titolo 62"
                        },
                        new
                        {
                            Id = 63,
                            Body = "Body 63",
                            Title = "Titolo 63"
                        },
                        new
                        {
                            Id = 64,
                            Body = "Body 64",
                            Title = "Titolo 64"
                        },
                        new
                        {
                            Id = 65,
                            Body = "Body 65",
                            Title = "Titolo 65"
                        },
                        new
                        {
                            Id = 66,
                            Body = "Body 66",
                            Title = "Titolo 66"
                        },
                        new
                        {
                            Id = 67,
                            Body = "Body 67",
                            Title = "Titolo 67"
                        },
                        new
                        {
                            Id = 68,
                            Body = "Body 68",
                            Title = "Titolo 68"
                        },
                        new
                        {
                            Id = 69,
                            Body = "Body 69",
                            Title = "Titolo 69"
                        },
                        new
                        {
                            Id = 70,
                            Body = "Body 70",
                            Title = "Titolo 70"
                        },
                        new
                        {
                            Id = 71,
                            Body = "Body 71",
                            Title = "Titolo 71"
                        },
                        new
                        {
                            Id = 72,
                            Body = "Body 72",
                            Title = "Titolo 72"
                        },
                        new
                        {
                            Id = 73,
                            Body = "Body 73",
                            Title = "Titolo 73"
                        },
                        new
                        {
                            Id = 74,
                            Body = "Body 74",
                            Title = "Titolo 74"
                        },
                        new
                        {
                            Id = 75,
                            Body = "Body 75",
                            Title = "Titolo 75"
                        },
                        new
                        {
                            Id = 76,
                            Body = "Body 76",
                            Title = "Titolo 76"
                        },
                        new
                        {
                            Id = 77,
                            Body = "Body 77",
                            Title = "Titolo 77"
                        },
                        new
                        {
                            Id = 78,
                            Body = "Body 78",
                            Title = "Titolo 78"
                        },
                        new
                        {
                            Id = 79,
                            Body = "Body 79",
                            Title = "Titolo 79"
                        },
                        new
                        {
                            Id = 80,
                            Body = "Body 80",
                            Title = "Titolo 80"
                        },
                        new
                        {
                            Id = 81,
                            Body = "Body 81",
                            Title = "Titolo 81"
                        },
                        new
                        {
                            Id = 82,
                            Body = "Body 82",
                            Title = "Titolo 82"
                        },
                        new
                        {
                            Id = 83,
                            Body = "Body 83",
                            Title = "Titolo 83"
                        },
                        new
                        {
                            Id = 84,
                            Body = "Body 84",
                            Title = "Titolo 84"
                        },
                        new
                        {
                            Id = 85,
                            Body = "Body 85",
                            Title = "Titolo 85"
                        },
                        new
                        {
                            Id = 86,
                            Body = "Body 86",
                            Title = "Titolo 86"
                        },
                        new
                        {
                            Id = 87,
                            Body = "Body 87",
                            Title = "Titolo 87"
                        },
                        new
                        {
                            Id = 88,
                            Body = "Body 88",
                            Title = "Titolo 88"
                        },
                        new
                        {
                            Id = 89,
                            Body = "Body 89",
                            Title = "Titolo 89"
                        },
                        new
                        {
                            Id = 90,
                            Body = "Body 90",
                            Title = "Titolo 90"
                        },
                        new
                        {
                            Id = 91,
                            Body = "Body 91",
                            Title = "Titolo 91"
                        },
                        new
                        {
                            Id = 92,
                            Body = "Body 92",
                            Title = "Titolo 92"
                        },
                        new
                        {
                            Id = 93,
                            Body = "Body 93",
                            Title = "Titolo 93"
                        },
                        new
                        {
                            Id = 94,
                            Body = "Body 94",
                            Title = "Titolo 94"
                        },
                        new
                        {
                            Id = 95,
                            Body = "Body 95",
                            Title = "Titolo 95"
                        },
                        new
                        {
                            Id = 96,
                            Body = "Body 96",
                            Title = "Titolo 96"
                        },
                        new
                        {
                            Id = 97,
                            Body = "Body 97",
                            Title = "Titolo 97"
                        },
                        new
                        {
                            Id = 98,
                            Body = "Body 98",
                            Title = "Titolo 98"
                        },
                        new
                        {
                            Id = 99,
                            Body = "Body 99",
                            Title = "Titolo 99"
                        },
                        new
                        {
                            Id = 100,
                            Body = "Body 100",
                            Title = "Titolo 100"
                        },
                        new
                        {
                            Id = 101,
                            Body = "Body 101",
                            Title = "Titolo 101"
                        },
                        new
                        {
                            Id = 102,
                            Body = "Body 102",
                            Title = "Titolo 102"
                        },
                        new
                        {
                            Id = 103,
                            Body = "Body 103",
                            Title = "Titolo 103"
                        },
                        new
                        {
                            Id = 104,
                            Body = "Body 104",
                            Title = "Titolo 104"
                        },
                        new
                        {
                            Id = 105,
                            Body = "Body 105",
                            Title = "Titolo 105"
                        },
                        new
                        {
                            Id = 106,
                            Body = "Body 106",
                            Title = "Titolo 106"
                        },
                        new
                        {
                            Id = 107,
                            Body = "Body 107",
                            Title = "Titolo 107"
                        },
                        new
                        {
                            Id = 108,
                            Body = "Body 108",
                            Title = "Titolo 108"
                        },
                        new
                        {
                            Id = 109,
                            Body = "Body 109",
                            Title = "Titolo 109"
                        },
                        new
                        {
                            Id = 110,
                            Body = "Body 110",
                            Title = "Titolo 110"
                        },
                        new
                        {
                            Id = 111,
                            Body = "Body 111",
                            Title = "Titolo 111"
                        },
                        new
                        {
                            Id = 112,
                            Body = "Body 112",
                            Title = "Titolo 112"
                        },
                        new
                        {
                            Id = 113,
                            Body = "Body 113",
                            Title = "Titolo 113"
                        },
                        new
                        {
                            Id = 114,
                            Body = "Body 114",
                            Title = "Titolo 114"
                        },
                        new
                        {
                            Id = 115,
                            Body = "Body 115",
                            Title = "Titolo 115"
                        },
                        new
                        {
                            Id = 116,
                            Body = "Body 116",
                            Title = "Titolo 116"
                        },
                        new
                        {
                            Id = 117,
                            Body = "Body 117",
                            Title = "Titolo 117"
                        },
                        new
                        {
                            Id = 118,
                            Body = "Body 118",
                            Title = "Titolo 118"
                        },
                        new
                        {
                            Id = 119,
                            Body = "Body 119",
                            Title = "Titolo 119"
                        },
                        new
                        {
                            Id = 120,
                            Body = "Body 120",
                            Title = "Titolo 120"
                        },
                        new
                        {
                            Id = 121,
                            Body = "Body 121",
                            Title = "Titolo 121"
                        },
                        new
                        {
                            Id = 122,
                            Body = "Body 122",
                            Title = "Titolo 122"
                        },
                        new
                        {
                            Id = 123,
                            Body = "Body 123",
                            Title = "Titolo 123"
                        },
                        new
                        {
                            Id = 124,
                            Body = "Body 124",
                            Title = "Titolo 124"
                        },
                        new
                        {
                            Id = 125,
                            Body = "Body 125",
                            Title = "Titolo 125"
                        },
                        new
                        {
                            Id = 126,
                            Body = "Body 126",
                            Title = "Titolo 126"
                        },
                        new
                        {
                            Id = 127,
                            Body = "Body 127",
                            Title = "Titolo 127"
                        },
                        new
                        {
                            Id = 128,
                            Body = "Body 128",
                            Title = "Titolo 128"
                        },
                        new
                        {
                            Id = 129,
                            Body = "Body 129",
                            Title = "Titolo 129"
                        },
                        new
                        {
                            Id = 130,
                            Body = "Body 130",
                            Title = "Titolo 130"
                        },
                        new
                        {
                            Id = 131,
                            Body = "Body 131",
                            Title = "Titolo 131"
                        },
                        new
                        {
                            Id = 132,
                            Body = "Body 132",
                            Title = "Titolo 132"
                        },
                        new
                        {
                            Id = 133,
                            Body = "Body 133",
                            Title = "Titolo 133"
                        },
                        new
                        {
                            Id = 134,
                            Body = "Body 134",
                            Title = "Titolo 134"
                        },
                        new
                        {
                            Id = 135,
                            Body = "Body 135",
                            Title = "Titolo 135"
                        },
                        new
                        {
                            Id = 136,
                            Body = "Body 136",
                            Title = "Titolo 136"
                        },
                        new
                        {
                            Id = 137,
                            Body = "Body 137",
                            Title = "Titolo 137"
                        },
                        new
                        {
                            Id = 138,
                            Body = "Body 138",
                            Title = "Titolo 138"
                        },
                        new
                        {
                            Id = 139,
                            Body = "Body 139",
                            Title = "Titolo 139"
                        },
                        new
                        {
                            Id = 140,
                            Body = "Body 140",
                            Title = "Titolo 140"
                        },
                        new
                        {
                            Id = 141,
                            Body = "Body 141",
                            Title = "Titolo 141"
                        },
                        new
                        {
                            Id = 142,
                            Body = "Body 142",
                            Title = "Titolo 142"
                        },
                        new
                        {
                            Id = 143,
                            Body = "Body 143",
                            Title = "Titolo 143"
                        },
                        new
                        {
                            Id = 144,
                            Body = "Body 144",
                            Title = "Titolo 144"
                        },
                        new
                        {
                            Id = 145,
                            Body = "Body 145",
                            Title = "Titolo 145"
                        },
                        new
                        {
                            Id = 146,
                            Body = "Body 146",
                            Title = "Titolo 146"
                        },
                        new
                        {
                            Id = 147,
                            Body = "Body 147",
                            Title = "Titolo 147"
                        },
                        new
                        {
                            Id = 148,
                            Body = "Body 148",
                            Title = "Titolo 148"
                        },
                        new
                        {
                            Id = 149,
                            Body = "Body 149",
                            Title = "Titolo 149"
                        },
                        new
                        {
                            Id = 150,
                            Body = "Body 150",
                            Title = "Titolo 150"
                        },
                        new
                        {
                            Id = 151,
                            Body = "Body 151",
                            Title = "Titolo 151"
                        },
                        new
                        {
                            Id = 152,
                            Body = "Body 152",
                            Title = "Titolo 152"
                        },
                        new
                        {
                            Id = 153,
                            Body = "Body 153",
                            Title = "Titolo 153"
                        },
                        new
                        {
                            Id = 154,
                            Body = "Body 154",
                            Title = "Titolo 154"
                        },
                        new
                        {
                            Id = 155,
                            Body = "Body 155",
                            Title = "Titolo 155"
                        },
                        new
                        {
                            Id = 156,
                            Body = "Body 156",
                            Title = "Titolo 156"
                        },
                        new
                        {
                            Id = 157,
                            Body = "Body 157",
                            Title = "Titolo 157"
                        },
                        new
                        {
                            Id = 158,
                            Body = "Body 158",
                            Title = "Titolo 158"
                        },
                        new
                        {
                            Id = 159,
                            Body = "Body 159",
                            Title = "Titolo 159"
                        },
                        new
                        {
                            Id = 160,
                            Body = "Body 160",
                            Title = "Titolo 160"
                        },
                        new
                        {
                            Id = 161,
                            Body = "Body 161",
                            Title = "Titolo 161"
                        },
                        new
                        {
                            Id = 162,
                            Body = "Body 162",
                            Title = "Titolo 162"
                        },
                        new
                        {
                            Id = 163,
                            Body = "Body 163",
                            Title = "Titolo 163"
                        },
                        new
                        {
                            Id = 164,
                            Body = "Body 164",
                            Title = "Titolo 164"
                        },
                        new
                        {
                            Id = 165,
                            Body = "Body 165",
                            Title = "Titolo 165"
                        },
                        new
                        {
                            Id = 166,
                            Body = "Body 166",
                            Title = "Titolo 166"
                        },
                        new
                        {
                            Id = 167,
                            Body = "Body 167",
                            Title = "Titolo 167"
                        },
                        new
                        {
                            Id = 168,
                            Body = "Body 168",
                            Title = "Titolo 168"
                        },
                        new
                        {
                            Id = 169,
                            Body = "Body 169",
                            Title = "Titolo 169"
                        },
                        new
                        {
                            Id = 170,
                            Body = "Body 170",
                            Title = "Titolo 170"
                        },
                        new
                        {
                            Id = 171,
                            Body = "Body 171",
                            Title = "Titolo 171"
                        },
                        new
                        {
                            Id = 172,
                            Body = "Body 172",
                            Title = "Titolo 172"
                        },
                        new
                        {
                            Id = 173,
                            Body = "Body 173",
                            Title = "Titolo 173"
                        },
                        new
                        {
                            Id = 174,
                            Body = "Body 174",
                            Title = "Titolo 174"
                        },
                        new
                        {
                            Id = 175,
                            Body = "Body 175",
                            Title = "Titolo 175"
                        },
                        new
                        {
                            Id = 176,
                            Body = "Body 176",
                            Title = "Titolo 176"
                        },
                        new
                        {
                            Id = 177,
                            Body = "Body 177",
                            Title = "Titolo 177"
                        },
                        new
                        {
                            Id = 178,
                            Body = "Body 178",
                            Title = "Titolo 178"
                        },
                        new
                        {
                            Id = 179,
                            Body = "Body 179",
                            Title = "Titolo 179"
                        },
                        new
                        {
                            Id = 180,
                            Body = "Body 180",
                            Title = "Titolo 180"
                        },
                        new
                        {
                            Id = 181,
                            Body = "Body 181",
                            Title = "Titolo 181"
                        },
                        new
                        {
                            Id = 182,
                            Body = "Body 182",
                            Title = "Titolo 182"
                        },
                        new
                        {
                            Id = 183,
                            Body = "Body 183",
                            Title = "Titolo 183"
                        },
                        new
                        {
                            Id = 184,
                            Body = "Body 184",
                            Title = "Titolo 184"
                        },
                        new
                        {
                            Id = 185,
                            Body = "Body 185",
                            Title = "Titolo 185"
                        },
                        new
                        {
                            Id = 186,
                            Body = "Body 186",
                            Title = "Titolo 186"
                        },
                        new
                        {
                            Id = 187,
                            Body = "Body 187",
                            Title = "Titolo 187"
                        },
                        new
                        {
                            Id = 188,
                            Body = "Body 188",
                            Title = "Titolo 188"
                        },
                        new
                        {
                            Id = 189,
                            Body = "Body 189",
                            Title = "Titolo 189"
                        },
                        new
                        {
                            Id = 190,
                            Body = "Body 190",
                            Title = "Titolo 190"
                        },
                        new
                        {
                            Id = 191,
                            Body = "Body 191",
                            Title = "Titolo 191"
                        },
                        new
                        {
                            Id = 192,
                            Body = "Body 192",
                            Title = "Titolo 192"
                        },
                        new
                        {
                            Id = 193,
                            Body = "Body 193",
                            Title = "Titolo 193"
                        },
                        new
                        {
                            Id = 194,
                            Body = "Body 194",
                            Title = "Titolo 194"
                        },
                        new
                        {
                            Id = 195,
                            Body = "Body 195",
                            Title = "Titolo 195"
                        },
                        new
                        {
                            Id = 196,
                            Body = "Body 196",
                            Title = "Titolo 196"
                        },
                        new
                        {
                            Id = 197,
                            Body = "Body 197",
                            Title = "Titolo 197"
                        },
                        new
                        {
                            Id = 198,
                            Body = "Body 198",
                            Title = "Titolo 198"
                        },
                        new
                        {
                            Id = 199,
                            Body = "Body 199",
                            Title = "Titolo 199"
                        });
                });

            modelBuilder.Entity("Server.DataModel.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("PostTag", b =>
                {
                    b.HasOne("Server.DataModel.Post", null)
                        .WithMany()
                        .HasForeignKey("PostsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.DataModel.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
